name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Get Git Tag
        id: get_tag
        shell: cmd
        run: |
          git describe --tags --always --dirty="+dev" > git_tag.tmp
          set /p GIT_TAG=<git_tag.tmp
          echo GIT_TAG=%GIT_TAG%>> %GITHUB_ENV%
          del git_tag.tmp

      - name: Build Windows package
        shell: cmd
        run: pkg.bat

      - name: Build Windows Installer
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path output
          Expand-Archive -Path (Get-ChildItem dist/*.zip).FullName -DestinationPath output -Force
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: |
            dist/*.zip
            dist/*.exe

  build-macos:
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make pkg.sh executable
        run: chmod +x pkg.sh

      - name: Build macOS package
        run: ./pkg.sh

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist
          path: dist/*.dmg

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install NDK 21
        run: sdkmanager --install "ndk;21.4.7075529"

      - name: Install SDKMAN
        run: |
          curl -s "https://get.sdkman.io?rcupdate=false" | bash

      - name: Install and activate JDK via SDKMAN
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk env install
          echo "JAVA_HOME=$(sdk home java $(grep java .sdkmanrc | cut -d= -f2))" >> "$GITHUB_ENV"


      # - name: Use official Gradle distribution URL
      #   run: |
      #     sed -i 's|https\\://mirrors.cloud.tencent.com/gradle/|https\\://services.gradle.org/distributions/|' \
      #       proj.android/gradle/wrapper/gradle-wrapper.properties

      - name: Make gradlew executable
        run: chmod +x proj.android/gradlew

      - name: Build Android APK
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/21.4.7075529
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk env
          ./bld-android.sh release

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-dist
          path: dist/*.apk

  release:
    needs: [build-windows, build-macos, build-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-dist
          path: dist

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-dist
          path: dist

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
